// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcP2xS6GpDNp4OPrljy9-zESv5sYzoWm0',
    appId: '1:847266294084:web:efa76d00cf05b6f6ab8f11',
    messagingSenderId: '847266294084',
    projectId: 'flutter-food-app-42305',
    authDomain: 'flutter-food-app-42305.firebaseapp.com',
    storageBucket: 'flutter-food-app-42305.appspot.com',
    measurementId: 'G-JGCPQ471XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6NwSEjgtWHVm4ZR8ZIYO80--QQl_uOLA',
    appId: '1:847266294084:android:b3cb6d171ddafd88ab8f11',
    messagingSenderId: '847266294084',
    projectId: 'flutter-food-app-42305',
    storageBucket: 'flutter-food-app-42305.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbWR-Yauttjtnd-6Iap1-HGT2pDFsScY4',
    appId: '1:847266294084:ios:58f67696c1890cc0ab8f11',
    messagingSenderId: '847266294084',
    projectId: 'flutter-food-app-42305',
    storageBucket: 'flutter-food-app-42305.appspot.com',
    iosClientId: '847266294084-7ipi7jbgn7qph9i7etreib9471b465v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbWR-Yauttjtnd-6Iap1-HGT2pDFsScY4',
    appId: '1:847266294084:ios:58f67696c1890cc0ab8f11',
    messagingSenderId: '847266294084',
    projectId: 'flutter-food-app-42305',
    storageBucket: 'flutter-food-app-42305.appspot.com',
    iosClientId: '847266294084-7ipi7jbgn7qph9i7etreib9471b465v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
